### ISSUE TITLE
Issue: It is calling four times. it must call ones.

### ISSUE THREAD

**Issue by Hareesh108** [Neha/react-19-examples#2]
Hii @Neha Dii..

have look at your example for fetching users. it is calling four times. 
how we can optimize this? 

![Screenshot from 2024-05-25 11-54-15](https://github.com/Neha/react-19-examples/assets/72018706/e59ab32a-4622-425d-898b-2bbf38be1cc5)
-57db-48de-bb48-a90b374fcb4c)

**Comment by Neha** [comment]
This is happening because of the use() and SSR. There is no caching and memo. 
In addition to the SSR, we are at the dev mode. So, a few extra calls.

to optimize this, either move to CSR - useEffect(), and data fetch library.

or  use: 

```
import { unstable_cache } from "react";

const fetchPosts = unstable_cache(async () => {
    const res = await fetch('https://jsonplaceholder.typicode.com/users');
    return res.json();
}, []); // Use a stable cache key

```
