### ISSUE TITLE
Problem with 'use' hook: infinite requests !

### ISSUE THREAD

**Issue by SRayen** [Neha/react-19-examples#6]
![image](https://github.com/user-attachments/assets/01b5ef4d-ecf3-4639-8ac1-02918198c80d)

![image](https://github.com/user-attachments/assets/978a8c8f-0e9f-4239-9587-e14196364238)

**Comment by Neha** [comment]
Hello @SRayen , thank you for logging the issue. The fix has been merged in the main. Please check.

**Comment by SRayen** [comment]
Thank you for the quick fix! I’ve tested it, and everything is running well now. Great work! 🚀
